# Generated by Django 4.2 on 2023-04-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'language',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Lenguage',
        ),
    ]
